### ISSUE TITLE
Implementar autenticación jwt

### ISSUE THREAD

**Issue by guivern** [GuiverCode/TodoApi#8]
****

**Comment by gvmcfly** [comment]
Fuente: https://auth0.com/blog/securing-asp-dot-net-core-2-applications-with-jwts/

**Comment by gvmcfly** [comment]
Agregar estos valores al final del archivo json appSettings.Development:
 ```
"JwtKey": "H2DO1TICP2PKXGG6",
  "JwtIssuer": "localhost",
  "JwtAudience": "localhost",
  "JwtExpireDays": 30
```
